apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "persistent-volume-ebs"
  labels:
    name: pv-ebs 
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi" 
  resources: request
  accessModes:
    - "ReadWriteMany"
  awsElasticBlockStore: 
    fsType: "ext4"
    volumeID: "{{EBS_VOLUME_ID}}"